name: CI

on: [push]

jobs:
  build:

    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v1
    
    - name: Setup msbuild
      uses: microsoft/setup-msbuild@v1
      
    - name: Setup nuget
      uses: warrenbuckley/Setup-Nuget@v1
      
    - name: Nuget restore
      run: nuget restore HSPI_SharkRobot.sln
      
    - name: MSBuild
      run: |
        msbuild /p:Configuration=Debug HSPI_SharkRobot.sln
        msbuild /p:Configuration=Release HSPI_SharkRobot.sln
        
    - name: Stage artifacts
      run: |
        mkdir artifacts
        cp HSPI_SharkRobot\bin\Release\HSPI_SharkRobot.exe artifacts\HSPI_SharkRobot.exe
        cp HSPI_SharkRobot.exe.config artifacts\HSPI_SharkRobot.exe.config
        cp install.txt artifacts\install.txt
    
    - name: Stage debug artifacts
      run: |
        mkdir artifacts-debug
        cp HSPI_SharkRobot\bin\Debug\HSPI_SharkRobot.exe "artifacts-debug\HSPI_SharkRobot.exe"
        cp HSPI_SharkRobot.exe.config artifacts-debug\HSPI_SharkRobot.exe.config
    
    - name: Upload artifacts
      uses: actions/upload-artifact@v1
      with:
        name: Plugin
        path: artifacts
    
    - name: Upload debug artifacts
      uses: actions/upload-artifact@v1
      with:
        name: Debug Build
        path: artifacts-debug
